### ISSUE TITLE
levantar instancia DB

### ISSUE THREAD

**Issue by gonzalo991** [Los-Chiperos/Reciclarg#9]

**Comment by NicolasZelarayan** [comment]
si estan de acuerdo y para que sea accesible la base se la levantaria en una instancia de GCP para poder acceder por ip con credenciales de acceso

**Comment by NicolasZelarayan** [comment]
se levanto instancia en GCP con motor MYSQL la ip de conexion es 34.176.243.185 
usuario: root
pass: reciclarg

**Comment by NicolasZelarayan** [comment]
dns de base de datos: base.reciclarg.cloud credenciales de acceso provisoriamente se conserva usuario root y reciclarg
